### ISSUE TITLE
Sensorless Homing

### ISSUE THREAD

**Issue by itsdylan** [hillsoftware/sv06#2]
If maxing the sensitivity, 255, the extruder still grinds along the left side.  I experienced this issue on the last build as well.

Further, I continually receive TMC connection error on this build. This may be related.

**Comment by hillsoftware** [comment]
TMC connection is definitely related as that is how communication with the stepper is obtained.  Short of a bad flash, I don't see any obvious software problem especially since it works for others. If you are trying the UBL build, try the bi-linear one or vice versa and let me know if it has the same issue.

I am assuming if you go back to stock firmware everything is fine?

**Comment by itsdylan** [comment]
I have determined the issue: you setup the build env GD32F103RET6_sovol_maple to but it should be STM32F103RET6_sovol_maple

**Comment by hillsoftware** [comment]
I would need to see your specific changes, but the GD env setup is basically just what the sovol was, but referring to just the GD processor versus the company Sovol.
